# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   id: 'Build container image'
#   args: [
#     'build',
#     '-f',
#     '/train.dockerfile',
#     '-t',
#     '${_IMAGE_NAME}',
#     '.',
#   ]
# - name: 'gcr.io/cloud-builders/docker'
#   id: 'Push container image'
#   args: [
#     'push',
#     '${_IMAGE_NAME}'
#   ]
# options:
#   logging: CLOUD_LOGGING_ONLY
# substitutions:
#   _IMAGE_NAME: 'europe-west4-docker.pkg.dev/dtup-mlop/corruptmnist/corruptmnist:latest'
# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'build', '-f', '${_FILE}', -t', 'europe-west4-docker.pkg.dev/dtup-mlop/corruptmnist/corruptmnist:latest', '.' ]
# images:
# - 'europe-west4-docker.pkg.dev/dtup-mlop/corruptmnist/corruptmnist:latest'
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', '${_FILE}', '-t', 'europe-west4-docker.pkg.dev/dtup-mlop/corruptmnist/corruptmnist:latest', '.']
    id: 'build-and-push-docker-image'
images:
  - 'europe-west4-docker.pkg.dev/dtup-mlop/corruptmnist/corruptmnist:latest'
timeout: '1200s'